export const styleManagerConfig = {
  sectors: [
    {
      name: "General",
      open: true,
      buildProps: [
        "display",
        "position",
        "float",
        "z-index",
        "top",
        "right",
        "bottom",
        "left",
        "object-position",
      ],
      properties: [
        { name: "Display", property: "display" },
        { name: "Position", property: "position" },
        { name: "Float", property: "float" },
        {
          property: "z-index",
          type: "integer",
          default: "0",
          step: 1,
          min: 0,
        },
        {
          property: "object-position",
          type: "composite",
          properties: [
            {
              property: "object-position-x",
              name: "X",
              type: "number",
              units: ["%", "px"],
              default: "50%",
            },
            {
              property: "object-position-y",
              name: "Y",
              type: "number",
              units: ["%", "px"],
              default: "50%",
            },
          ],
          name: "Object Position",
        },
      ],
    },
    {
      name: "Dimension",
      open: false,
      buildProps: [
        "width",
        "height",
        "max-width",
        "max-height",
        "min-width",
        "min-height",
        "padding",
        "margin",
      ],
      properties: [
        { name: "Width", property: "width" },
        { name: "Height", property: "height" },
        { name: "Padding", property: "padding" },
        { name: "Margin", property: "margin" },
      ],
    },
    {
      name: "Typography",
      open: false,
      buildProps: [
        "font-family",
        "font-size",
        "font-weight",
        "letter-spacing",
        "line-height",
        "color",
        "text-align",
        "text-shadow",
      ],
      properties: [
        {
          name: "Font Family",
          property: "font-family",
          type: "select",
          defaults: "Arial",
          options: [
            { id: "Arial", label: "Arial", value: "Arial" },
            { id: "Arial Black", label: "Arial Black", value: "Arial Black" },
            {
              id: "Brush Script MT",
              label: "Brush Script MT",
              value: "Brush Script MT",
            },
            {
              id: "Conic Sans MS",
              label: "Conic Sans MS",
              value: "Conic Sans MS",
            },
            { id: "Helvetica", label: "Helvetica", value: "Helvetica" },
            {
              id: "Times New Roman",
              label: "Times New Roman",
              value: "Times New Roman",
            },
            { id: "Courier New", label: "Courier New", value: "Courier New" },
            { id: "Impact", label: "Impact", value: "Impact" },
            {
              id: "Lucida Sans Unicode",
              label: "Lucida Sans Unicode",
              value: "Lucida Sans Unicode",
            },
            { id: "Georgia", label: "Georgia", value: "Georgia" },
            { id: "Tahoma", label: "Tahoma", value: "Tahoma" },
            {
              id: "Trebuchet Ms",
              label: "Trebuchet Ms",
              value: "Trebuchet Ms",
            },
            { id: "Verdana", label: "Verdana", value: "Verdana" },
          ],
        },
        {
          name: "Font Size",
          property: "font-size",
          type: "integer",
          units: ["px", "em", "rem", "%"],
          defaults: "16px",
        },
      ],
    },
    {
      name: "Flex",
      open: false,
      buildProps: [
        "flex-direction",
        "flex-wrap",
        "justify-content",
        "align-items",
        "align-content",
      ],
      properties: [
        {
          name: "Flex Direction",
          property: "flex-direction",
          type: "select",
          defaults: "row",
          options: [
            { id: "row", label: "row", value: "row" },
            { id: "row-reverse", label: "row-reverse", value: "row-reverse" },
            { id: "column", label: "column", value: "column" },
            {
              id: "column-reverse",
              label: "column-reverse",
              value: "column-reverse",
            },
          ],
        },
        {
          name: "Flex Wrap",
          property: "flex-wrap",
          type: "select",
          defaults: "nowrap",
          options: [
            { id: "nowrap", label: "nowrap", value: "nowrap" },
            {
              id: "wrap-reverse",
              label: "wrap-reverse",
              value: "wrap-reverse",
            },
            { id: "wrap", label: "wrap", value: "wrap" },
          ],
        },
        {
          name: "Justify content",
          property: "justify-content",
          type: "select",
          defaults: "flex-start",
          options: [
            { id: "flex-start", label: "flex-start", value: "flex-start" },
            { id: "flex-end", label: "flex-end", value: "flex-end" },
            { id: "center", label: "center", value: "center" },
            {
              id: "space-between",
              label: "space-between",
              value: "space-between",
            },
            {
              id: "space-around",
              label: "space-around",
              value: "space-around",
            },
            {
              id: "space-evenly",
              label: "space-evenly",
              value: "space-evenly",
            },
          ],
        },
        {
          name: "Align Items",
          property: "align-items",
          type: "select",
          defaults: "flex-start",
          options: [
            { id: "flex-start", label: "flex-start", value: "flex-start" },
            { id: "flex-end", label: "flex-end", value: "flex-end" },
            { id: "center", label: "center", value: "center" },
            {
              id: "space-between",
              label: "space-between",
              value: "space-between",
            },
            {
              id: "space-around",
              label: "space-around",
              value: "space-around",
            },
            {
              id: "stretch",
              label: "stretch",
              value: "stretch",
            },
          ],
        },
        {
          name: "Align content",
          property: "align-content",
          type: "select",
          defaults: "stretch",
          options: [
            { id: "flex-start", label: "flex-start", value: "flex-start" },
            { id: "flex-end", label: "flex-end", value: "flex-end" },
            { id: "center", label: "center", value: "center" },
            {
              id: "baseline",
              label: "baseline",
              value: "baseline",
            },
            {
              id: "stretch",
              label: "stretch",
              value: "stretch",
            },
          ],
        },
      ],
    },
    {
      name: "Decorations",
      open: false,
      buildProps: [
        "background-color",
        "background-image",
        "background",
        "border",
        "box-shadow",
        "border-radius",
      ],
      properties: [
        {
          name: "Background Color",
          property: "background-color",
          type: "color",
        },
        {
          name: "Background Image",
          property: "background-image",
          type: "file",
          functionName: "url",
        },
        {
          name: "Background Image property",
          property: "background",
          type: "composite",
          properties: [
            {
              name: "Repeat",
              property: "background-repeat",
              type: "select",
              defaults: "repeat",
              options: [
                { id: "no-repeat", label: "No Repeat", value: "no-repeat" },
                { id: "repeat", label: "Repeat", value: "repeat" },
                {
                  id: "repeat-x",
                  label: "Repeat Horizontally",
                  value: "repeat-x",
                },
                {
                  id: "repeat-y",
                  label: "Repeat Vertically",
                  value: "repeat-y",
                },
              ],
            },
            {
              name: "Position",
              property: "background-position",
              type: "select",
              defaults: "left-top",
              options: [
                { id: "left-top", label: "Left Top", value: "left top" },
                {
                  id: "left-center",
                  label: "Left Center",
                  value: "left center",
                },
                {
                  id: "left-bottom",
                  label: "Left Bottom",
                  value: "left bottom",
                },
                { id: "right-top", label: "Right Top", value: "right top" },
                {
                  id: "right-center",
                  label: "Right Center",
                  value: "right center",
                },
                {
                  id: "right-bottom",
                  label: "Right Bottom",
                  value: "right bottom",
                },
                { id: "center-top", label: "Center Top", value: "center top" },
                {
                  id: "center-center",
                  label: "Center Center",
                  value: "center center",
                },
                {
                  id: "center-bottom",
                  label: "Center Bottom",
                  value: "center bottom",
                },
              ],
            },
            {
              name: "Attachment",
              property: "background-attachment",
              type: "select",
              defaults: "scroll",
              options: [
                { id: "scroll", label: "Scroll", value: "scroll" },
                { id: "fixed", label: "Fixed", value: "fixed" },
                { id: "local", label: "Local", value: "local" },
              ],
            },
            {
              name: "Size",
              property: "background-size",
              type: "select",
              defaults: "auto",
              options: [
                { id: "auto", label: "Auto", value: "auto" },
                { id: "cover", label: "Cover", value: "cover" },
                { id: "contain", label: "Contain", value: "contain" },
              ],
            },
          ],
        },
        {
          name: "Border",
          property: "border",
          type: "composite",
          properties: [
            {
              name: "Border Width",
              property: "border-width",
              type: "integer",
              units: ["px"],
            },
            {
              name: "Border Style",
              property: "border-style",
              type: "select",
              options: [
                { id: "none", label: "None", value: "none" },
                { id: "solid", label: "Solid", value: "solid" },
                { id: "dashed", label: "Dashed", value: "dashed" },
                { id: "dotted", label: "Dotted", value: "dotted" },
              ],
            },
            {
              name: "Border Color",
              property: "border-color",
              type: "color",
            },
          ],
        },
        { name: "Box Shadow", property: "box-shadow", type: "composite" },
        {
          name: "Border Radius",
          property: "border-radius",
          type: "composite",
        },
        {
          name: "Object Fit",
          property: "object-fit",
          type: "select",
          defaults: "fill",
          options: [
            { id: "fill", label: "Fill", value: "fill" },
            { id: "contain", label: "Contain", value: "contain" },
            { id: "cover", label: "Cover", value: "cover" },
            { id: "none", label: "None", value: "none" },
            { id: "scale-down", label: "Scale Down", value: "scale-down" },
          ],
        },
      ],
    },
    {
      name: "Extra",
      open: false,
      buildProps: ["opacity", "overflow", "cursor", "visibility"],
      properties: [
        {
          name: "Opacity",
          property: "opacity",
          type: "integer",
          step: 0.1,
          min: 0,
          max: 1,
        },
        {
          name: "Overflow",
          property: "overflow",
          type: "select",
          options: [
            { id: "visible", label: "Visible", value: "visible" },
            { id: "hidden", label: "Hidden", value: "hidden" },
            { id: "scroll", label: "Scroll", value: "scroll" },
            { id: "auto", label: "Auto", value: "auto" },
          ],
        },
        {
          name: "Cursor",
          property: "cursor",
          type: "select",
          options: [
            { id: "default", label: "Default", value: "default" },
            { id: "pointer", label: "Pointer", value: "pointer" },
            { id: "move", label: "Move", value: "move" },
            { id: "text", label: "Text", value: "text" },
          ],
        },
        {
          name: "Visibility",
          property: "visibility",
          type: "select",
          options: [
            { id: "visible", label: "Visible", value: "visible" },
            { id: "hidden", label: "Hidden", value: "hidden" },
          ],
        },
        {
          name: "Vertical Align",
          property: "vertical-align",
          type: "select",
          defaults: "baseline",
          options: [
            { id: "baseline", label: "Baseline", value: "baseline" },
            { id: "top", label: "Top", value: "top" },
            { id: "middle", label: "Middle", value: "middle" },
            { id: "bottom", label: "Bottom", value: "bottom" },
            { id: "text-top", label: "Text Top", value: "text-top" },
            { id: "text-bottom", label: "Text Bottom", value: "text-bottom" },
            { id: "sub", label: "Sub", value: "sub" },
            { id: "super", label: "Super", value: "super" },
          ],
        },
      ],
    },
    {
      name: "Animation",
      open: false,
      buildProps: ["transition", "transform"],
    },
  ],
};
